spring.application.name=task
# H2 Database Settings
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Liquibase Settings
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true